"""rich text post

Revision ID: 202b9e78dfe
Revises: 286c348a798
Create Date: 2015-03-02 12:27:36.535150

"""

# revision identifiers, used by Alembic.
revision = '202b9e78dfe'
down_revision = '286c348a798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
