"""modify User model

Revision ID: 2b5bec776b8
Revises: 23d9f68ecd3
Create Date: 2015-02-25 15:42:03.699594

"""

# revision identifiers, used by Alembic.
revision = '2b5bec776b8'
down_revision = '23d9f68ecd3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
