"""add dynamic lazy

Revision ID: 4ad6e783ba8
Revises: 3b032cf3d74
Create Date: 2015-02-16 10:02:36.483049

"""

# revision identifiers, used by Alembic.
revision = '4ad6e783ba8'
down_revision = '3b032cf3d74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
