"""followers

Revision ID: a5bf7c8cbf
Revises: 415c8a6e412
Create Date: 2015-03-02 20:21:29.147827

"""

# revision identifiers, used by Alembic.
revision = 'a5bf7c8cbf'
down_revision = '415c8a6e412'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
